### ISSUE TITLE
Error for fuel pressure input

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [FOME-Tech/fome-fw#111]
i still get this popping up from time to time.  this occurance was after writing the lemons tune to a new ecu. power cycling does clear the error.  

![image](https://github.com/FOME-Tech/fome-fw/assets/82395131/f198d173-aac3-4237-97e7-fc3dbe53b722)

**Comment by mck1117** [comment]
I saw this too writing my tune after a firmware update

**Comment by mck1117** [comment]
fixed!
