### ISSUE TITLE
Cannot use fuel pressure compensation with a canbus fuel pressure sensor

### ISSUE THREAD

**Issue by ZHoob2004** [FOME-Tech/fome-fw#117]
I'm using a hellen96 as a primary ECU with some additional sensors on MRE broadcast over can. The hellen imports some sensor values (including fuel pressure) via LUA. When fuel pressure compensation is enabled and the sensor left unconfigured on the primary ecu, the ecu encounters a fatal error on startup due to the missing fuel pressure sensor.

**Comment by mck1117** [comment]
It now no longer generates an error, it just warns, so you can add the sensor from Lua without the ECU complaining at startup.
