### ISSUE TITLE
Broken ts tips after auto log field generation change

### ISSUE THREAD

**Issue by OrchardPerformance** [FOME-Tech/fome-fw#144]
![Screenshot_20230102-125822_GitHub](https://user-images.githubusercontent.com/49926376/210235194-b4d89ba2-b899-48f4-a608-e45d1268dc88.jpg)

https://github.com/rusefi/rusefi/commit/e50c67862367eb5972d8e104d2265f50b6948d1f#diff-46e1f984fe68d0a10452477abd40022fe895c9fe392a586dc2f2180752297a49

**Comment by OrchardPerformance** [comment]
@nmschulte poke so we can close this if it's a non-issue.

**Comment by nmschulte** [comment]
I'll get at it this week; my ECU's been in garage purgatory.

I believe this is still an issue, but I forget the details.

**Comment by nmschulte** [comment]
> @nmschulte is this still true?

The issue I reported there is fixed via commits referenced in https://github.com/rusefi/rusefi/issues/4927.

Closing this now.

**Comment by nmschulte** [comment]
ex:

> This is just my observation from e.g. 5 ft pole -- perhaps I misunderstand the intent behind these comments.

Some specific examples, though pretty much any config in rusefi_config.txt with a new-line seems like it'd be useful to have the full comment in TunerStudio:

https://github.com/rusefi/rusefi/blob/master/firmware/integration/rusefi_config.txt#L302

```
float baseFuel;Base mass of the per-cylinder fuel injected during cranking. This is then modified by the multipliers for CLT, IAT, TPS ect, to give the final cranking pulse width.\nA reasonable starting point is 60mg per liter per cylinder.\nex: 2 liter 4 cyl = 500cc/cyl, so 30mg cranking fuel.;"mg", 1, 0, 0, 500, 1
int16_t rpm;This sets the RPM limit below which the ECU will use cranking fuel and ignition logic, typically this is around 350-450rpm. \nset cranking_rpm X;"RPM", 1, 0, 0, 3000, 0
end_struct
```

![image](https://github.com/FOME-Tech/fome-fw/assets/8540239/dfba164e-0f91-491c-b29b-6888a720ff27)
