### ISSUE TITLE
VVT target tables

### ISSUE THREAD

**Issue by OrchardPerformance** [FOME-Tech/fome-fw#147]
Feature TS Notes:
Feature Status:
Known Problems:
Priority:
Suggested Fix:
Related Tickets:

Note -

![image](https://user-images.githubusercontent.com/49926376/209923186-2a825981-ea64-425c-9927-8fc477a93d3b.png)

**Comment by mck1117** [comment]
> What is the default table that comes up on proteus?

all zeroes

> Any usability issues with the tables, do we need less that 1 degree steps?

I don't think so, no. I've never seen an OEM table that wasn't integer degrees. If you're tuning <1 degree target accuracy on your cams, you're probably in the wrong place.

**Comment by mck1117** [comment]
Don't think there's anything to do here.
