### ISSUE TITLE
Small pulse correction Ford style

### ISSUE THREAD

**Issue by OrchardPerformance** [FOME-Tech/fome-fw#151]
Feature TS Notes:
Feature Status:
Known Problems:
Priority:
Suggested Fix:
Related Tickets:

Note - 

![image](https://user-images.githubusercontent.com/49926376/209882310-605dc307-4b9e-494f-86ee-df1d296614e1.png)

**Comment by mck1117** [comment]
7de17eae7e0c6758344c13c250d0ca7f26ef19cb covers this one too
