### ISSUE TITLE
Does VVT_FIRST_HALF need to exist?

### ISSUE THREAD

**Issue by mck1117** [FOME-Tech/fome-fw#176]
VVT_FIRST_HALF and VVT_SECOND_HALF do the same thing, and you can get one from the other by adding 360 to your trigger offset.

The problem with VVT_FIRST_HALF is that it can have unpredictable results on non-360 deg primary triggers, like 12 tooth crank for example.

VVT_SECOND_HALF:

(TDC is last primary tooth before cam tooth)

![image](https://github.com/FOME-Tech/fome-fw/assets/568254/c63d49c7-0126-4eb7-b27b-62dc1762e98e)

VVT_FIRST_HALF:

(TDC is _two_ teeth before cam tooth, that's odd?)

![image](https://github.com/FOME-Tech/fome-fw/assets/568254/1c5aac15-a84e-4be8-9f55-7a97c124f9ab)

Since these two modes do fundamentally the same thing, best option is maybe:

- VVT_FIRST_HALF -> delete
- VVT_SECOND_HALF -> VVT_SINGLE_TOOTH

**Comment by mck1117** [comment]
tangentially related 7ae11160d9bfb31a664130e66586e849b8201c8a

**Comment by OrchardPerformance** [comment]
Yep, I would tend to agree with that. I don't see why we need to treat the cam sync differently for 1st crank 360 vs 2nd crank 360. 
I have not seen it differentiated in anything else, normality is to assume 0 is TDC firing stroke and 720 is the max accepted offset. 

As long as we note to users in the wiki that some VVT offsets may need 360 degrees adding to the offset then I see no issue.

**Comment by mck1117** [comment]
VVT first/second half is gone, it's just single tooth mode now.
