### ISSUE TITLE
Knock Control : Usability of max knock retard table 

### ISSUE THREAD

**Issue by OrchardPerformance** [FOME-Tech/fome-fw#192]
Current max allowed knock retard table is just a table of degrees, requiring a user to subtract this from their ignition table to check if they are going to be past TDC/too retarded. 

We should make this a table of degrees relative to TDC, so a user only has to enter their desired worst case ignition timing. 

Current method will work, just requires more calculation hence the enhancement tag. 

![image](https://github.com/FOME-Tech/fome-fw/assets/49926376/3bbaaef2-d9f1-4578-bb5b-cbaf67f47515)

**Comment by mck1117** [comment]
Should this change if we still have a global min/max timing setting?

**Comment by OrchardPerformance** [comment]
Nahh, it's a pretty application specific requirement, we are trying to prevent insane egts as well as firing past tdc on wasted spark so it's quite load/rpm dependent.

**Comment by OrchardPerformance** [comment]
Played about with this the other day, needs a tool tip but that's a minor thing. 
Will create a tool tip ticket when we are sure it all works
