### ISSUE TITLE
Bench test improvements

### ISSUE THREAD

**Issue by mck1117** [FOME-Tech/fome-fw#219]
- add button for "abort test" (the scenario is that your injector test bucket is about to overflow or you started a longer test than you want)
- increase maximum count
- independent parameters for fuel/spark/etc

**Comment by 125jdavis** [comment]
- Fuel pressure gauge in "Injector test" window in TS would be useful.
- Add "Fuel pump on" button in injector test window so that fuel pump can be kept on via ECU during injector tests.

**Comment by 125jdavis** [comment]
- Injector test window does not specify which injector(s) are being tested. Do we want to actuate all injectors? I'm not sure if I have an opinion yet.
- Also, there is no "test" button, only "Burn".

**Comment by mck1117** [comment]
> Injector test window

Which injector test window? Screenshot?

**Comment by 125jdavis** [comment]
![image](https://github.com/FOME-Tech/fome-fw/assets/24885463/d5038a6e-e183-4d2e-94f3-882a0d42ad56)

**Comment by mck1117** [comment]
Used the new UI to flow test my fuel injectors, worked great!
