### ISSUE TITLE
Internal: build documentation refers to obsoleted Jenkins instead of Gradle

### ISSUE THREAD

**Issue by mi-hol** [FOME-Tech/fome-fw#220]
File found with incorrect information is:

[/.github/workflows/readme.md](https://github.com/mi-hol/fome-fw/blob/master/.github/workflows/readme.md)

**Comment by nmschulte** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams

https://mermaid.js.org/syntax/flowchart.html

```mermaid
flowchart TD
    gha_firmware["Firmware at GHA"]
    firmware_compile[["firmware/compile.sh"]]
    etc{{"..."}}
    gha_firmware --> firmware_compile
    firmware_compile --> etc
```
