### ISSUE TITLE
 do we need an option for two wire wasted and two wire batch?

### ISSUE THREAD

**Issue by mck1117** [FOME-Tech/fome-fw#23]
Do we need an option for two wire wasted? Why not just always do two wire wasted, and allow users to ignore some pins?

https://github.com/rusefi/rusefi/issues/4610

**Comment by OrchardPerformance** [comment]
We are now always 2 wire? 

Close this?

**Comment by mck1117** [comment]
We can also get rid of two wire batch (ie, always two wire batch), which will fix https://github.com/rusefi/rusefi/issues/5353
