### ISSUE TITLE
Ethanol Content Sensor Sensitivity

### ISSUE THREAD

**Issue by classicdaily** [FOME-Tech/fome-fw#266]
Add some sort of sensitivity/sample rate adjustment to the ethanol sensor. 
Or Lock Ethanol content above above TPS/RPM/ETC

Issue is that ethanol content changes at high RPM/Flow and changes the fueling.

**Comment by mck1117** [comment]
Not that I don't believe you, but do you have a log demonstrating this behavior? Just want to see what it looks like in the wild so we can do the right thing.

**Comment by mck1117** [comment]
@classicdaily ping on this

**Comment by mck1117** [comment]
looks like we can close this, @classicdaily if it comes back, repoen?

**Comment by classicdaily** [comment]
Yes sounds good.

I didn’t have any issue on the last car I tuned with e85.

www.classicdaily.net
