### ISSUE TITLE
Adding CanBus Support for AEM Series X Wideband Gauge/Controller  30-0300

### ISSUE THREAD

**Issue by c0nvexo** [FOME-Tech/fome-fw#268]
AEM has support for AEMNet/CanBus integration for communicating with third party devices. Here's the corresponding  documentation for it, specifically at pages 10 and 11.

[techlibrary_30-0300_x-series_wideband_uego_afr_sensor_gauge.pdf](https://github.com/FOME-Tech/fome-fw/files/12887813/techlibrary_30-0300_x-series_wideband_uego_afr_sensor_gauge.pdf)

**Comment by mck1117** [comment]
Oh, wait, it's an x-series? That's already supported! Just wire it up, enable CAN wideband, and it'll work.
