### ISSUE TITLE
Second VVT bank PID settings read outside of array

### ISSUE THREAD

**Issue by rusefillc** [FOME-Tech/fome-fw#271]
```
	// Use the same settings for the Nth cam in every bank (ie, all exhaust cams use the same PID)
	m_pid.initPidClass(&engineConfiguration->auxPid[index]);
```

https://github.com/rusefi/rusefi/commit/680d18e4338059b1d7fd47efc0ec088abbc8333a#diff-8b9678ed282bfa69ef645268095b8351a040beb58e367fbd6273a6d02eae5633

**Comment by mck1117** [comment]
fixed in d040e0982c7b0a5437b851099997d375f15609b0
