### ISSUE TITLE
TS tip fix - priming fuel pulse. 

### ISSUE THREAD

**Issue by OrchardPerformance** [FOME-Tech/fome-fw#372]
Not sure this is correct. 
![image](https://github.com/FOME-Tech/fome-fw/assets/49926376/3d1ff06d-0aa5-4c41-a815-84b025404cc3)

**Comment by mck1117** [comment]
you have the priming delay selected, so that's the tip it shows at the bottom

**Comment by OrchardPerformance** [comment]
ha, yes, fuck, time for bed.

d...delete this.
