### ISSUE TITLE
toyota 3 tooth weirdness

### ISSUE THREAD

**Issue by mck1117** [FOME-Tech/fome-fw#382]
> He's seeing an issue where sometimes it looks like the cam decoder is picking up on the wrong tooth.

> If he gets a high VVT angle (120+) as the ECU is powered, endless cranking won't change that.   If it's low (near 0) it'll start fine.

Here's the bad behavior:

https://github.com/FOME-Tech/fome-fw/assets/568254/cf85ad62-6b20-4a31-ae11-6bc12c4e3edc

[matches_vid.zip](https://github.com/FOME-Tech/fome-fw/files/14564563/matches_vid.zip)

Waiting on a snip of engine sniffer, and a log of good behavior.

**Comment by mck1117** [comment]
Engine sniffer from the same car

![fome_screen-1](https://github.com/FOME-Tech/fome-fw/assets/568254/15cfdf36-ec56-411e-9c2d-6ea8638d4074)

**Comment by mck1117** [comment]
This cam tooth is very close to the sync point

![image](https://github.com/FOME-Tech/fome-fw/assets/568254/53667c1c-e38d-4a79-8ca7-72938147dcd0)

**Comment by diy-efi** [comment]
[1g-fe with cam wired.zip](https://github.com/FOME-Tech/fome-fw/files/14578750/1g-fe.with.cam.wired.zip)

This is a salee log from the development car I had briefly.

Wiring 
E23 (crank +)  VR1+ (on max9926)
E22 (crank -) VR1- (on max9926)

E10 (cam +) VR2+  (on max9926)
New wire (cam -) VR2- on max9926)
E10 is also a new wire (shielded pair with cam -   but used OEM pin number for clarity.

**Comment by diy-efi** [comment]
[1g-fe with cam wired.zip](https://github.com/FOME-Tech/fome-fw/files/14578830/1g-fe.with.cam.wired.zip)

**Comment by diy-efi** [comment]
With Dynferus's friend, correcting the VR polarity to match what I have on the PnP he has now had the same issue.
That is 3 confirmed non start / vvt jumping to 120 degree replications on different cars.

A suggestion I made is to add a new setting in advanced trigger to ignore the cam below a certain RPM.

![image](https://github.com/FOME-Tech/fome-fw/assets/56509135/4cf52365-cfed-467c-8e29-2bd1ac446bb1)

**Comment by mck1117** [comment]
fixed!
