### ISSUE TITLE
permissive license or restrictive license?

### ISSUE THREAD

**Issue by rusefillc** [FOME-Tech/fome-fw#383]
* https://github.com/FOME-Tech/fome-fw/blob/master/LICENSE is it asking for an s///?
* "f" stands for "free" yet https://github.com/FOME-Tech/fome-fw/blob/master/LICENSE a restrictive license like the General Public License (GPL)?

**Comment by mck1117** [comment]
> "f" stands for "free" yet https://github.com/FOME-Tech/fome-fw/blob/master/LICENSE a restrictive license like the General Public License (GPL)?

https://en.wikipedia.org/wiki/GNU_General_Public_License

> The GNU General Public License (GNU GPL or simply GPL) is a series of widely used [free software licenses](https://en.wikipedia.org/wiki/Free_software_license)

**Comment by rusefillc** [comment]
My bad should have created two separate issues https://github.com/FOME-Tech/fome-fw/issues/384
