### ISSUE TITLE
false "FOME Simulator program not found" due to invalid SIMULATOR_BINARY_PATH

### ISSUE THREAD

**Issue by rusefillc** [FOME-Tech/fome-fw#394]
Download bundle, unzip bundle
Launch console

Actual result:
console fails to locate simulator
``private static final String SIMULATOR_BINARY_PATH = "../simulator/build";`` seems to be issue?

![image](https://github.com/FOME-Tech/fome-fw/assets/48498823/5a1f6d18-d52e-4595-836f-af84fa4f6def)

**Comment by nmschulte** [comment]
Looking, probably due to https://github.com/FOME-Tech/fome-fw/pull/378

**Comment by nmschulte** [comment]
I wonder actually if it's the added `canExecute()` check: https://github.com/FOME-Tech/fome-fw/pull/378/files#diff-c4208a0f2492980deaa068a590d5d3fcdbf503ccea7b7e29f8733c7996df39ceR108
```java
        if (!binary.exists() || binary.isDirectory() || !binary.canExecute()) {
```
IIUC, Console will use a different path than that of `SimulatorExecHelper`: https://github.com/FOME-Tech/fome-fw/pull/378/files#diff-bd5c3c893b546d5e8f982a022ab3a552179c982bedf08776b65d42ebde23f190R17
```java
private static final String SIMULATOR_BINARY_PATH = "./";
```

**Comment by nmschulte** [comment]
On my machine, when I:
```sh
cd fome.release_2312.f407-discovery/console/
java -jar fome_console.jar
```

I don't see the same behavior:
![image](https://github.com/FOME-Tech/fome-fw/assets/8540239/2b0b1560-14ba-484e-bc33-77ea97f60047)

**Comment by nmschulte** [comment]
Also, not sure why the bundled `fome_console.jar` shows _Version 20230220_ but the `fome_console.exe` shows _Version 20231228_.

**Comment by mck1117** [comment]
> On my machine, 

is this a windows machine?

**Comment by nmschulte** [comment]
> > On my machine,
> 
> is this a windows machine?

I don't have one of those handy; can someone with a Windows machine give it a whirl?  Otherwise, I'll try to find one this week if I can.

**Comment by nmschulte** [comment]
@rusefillc can you see if this is fixed via #395 (snapshot build artifacts here: https://github.com/FOME-Tech/fome-fw/actions/runs/8728754078)?

**Comment by rusefillc** [comment]
fixed

![image](https://github.com/FOME-Tech/fome-fw/assets/48498823/184d703e-c4de-4d53-b531-2e9499868172)

simulator does not launch but that's a different issue

![image](https://github.com/FOME-Tech/fome-fw/assets/48498823/158f9f02-3aae-4ab5-9455-057408274838)

**Comment by rusefillc** [comment]
> 
> simulator does not launch but that's a different issue
> 

simulator.exe has disappeared from folder is it Win11 defender eating it?
