### ISSUE TITLE
Idle & Main Region swapped in Closed loop fueling

### ISSUE THREAD

**Issue by rk-iv** [FOME-Tech/fome-fw#425]
BMM proteus f7 board ECU, firmware 20240330

While Idling, changing the Idle Max add and remove percentage in Closed Loop Fueling does not seem to adjust the correct region. However, when Adjusting the Main region, it does works while idling.

My settings are very similar to the below

![image](https://github.com/FOME-Tech/fome-fw/assets/165811927/cfd549ef-ae1a-405c-b3b9-607ba39ebe86)

log attached of idling, and first adjusting idle region remove from 15 to 0, with no response from fuel trim, then changing main region remove from 15 to 0 at idle and having fuel trim respond.

[clfc_issue_2024-05-14_07.29.35.zip](https://github.com/FOME-Tech/fome-fw/files/15316598/clfc_issue_2024-05-14_07.29.35.zip)

**Comment by nmschulte** [comment]
The log shows that the determined CLF bin is always "main," (`fuelClosedLoopBinIdx` == 3) and presumably this is because the RPM is always > 1000 RPM: e.g. never actually idling.

![graph](https://github.com/FOME-Tech/fome-fw/assets/8540239/761d667e-bb44-42b1-b67d-0b01e656aba6)

**Comment by mck1117** [comment]
looks like it's working as intended....
