### ISSUE TITLE
Move all protection/limit features to the same category.

### ISSUE THREAD

**Issue by dynfer** [FOME-Tech/fome-fw#436]
Hello,

Im suggesting to move all limit and protection functions like knock, revlimiter, lean protection etc to follow a similar grouping like speeduino does as in screenshot below:

![obraz](https://github.com/FOME-Tech/fome-fw/assets/102673508/7524c2c7-8769-4efe-80fd-d7d4a90ee538)

**Comment by mck1117** [comment]
pretty much done, and improved oil pressure protection in #460
