### ISSUE TITLE
Lambda values 7 decimal places

### ISSUE THREAD

**Issue by duhafnusa4** [FOME-Tech/fome-fw#458]
Values for lambda going to the 7th decimal places seems excessive? Do we need that level of accuracy? ![image](https://github.com/user-attachments/assets/86d628ab-340a-4d33-8de4-776f9e6b5de1)

**Comment by mck1117** [comment]
please don't hand-inspect the msq file, that's an implementation detail of TS, not how we're storing them internally.

**Comment by duhafnusa4** [comment]
Unintentionally noticed that.10-4
