### ISSUE TITLE
Weird rpm spikes on Proteus and latest snapshot

### ISSUE THREAD

**Issue by dynfer** [FOME-Tech/fome-fw#469]
Overview:
1UZ-FE
36-2 VR crank into proteus VR1
single tooth cam into proteus VR2

RPM happens to drop below current real value happens at idle around 800-> 200rpm and during driving and steady conditions.
![obraz](https://github.com/user-attachments/assets/9403ae6f-04dd-4cd7-9a40-d3e626fe4e5b)

[długie_2.zip](https://github.com/user-attachments/files/16665206/dlugie_2.zip)

**Comment by dynfer** [comment]
![obraz](https://github.com/user-attachments/assets/925ffd06-a653-4d22-a4c9-14bfb97fb98f)
![obraz](https://github.com/user-attachments/assets/d926956e-90e1-485f-95b3-e7680f96fa0f)

**Comment by mck1117** [comment]
did this get resolved with better hardware?

**Comment by dynfer** [comment]
> did this get resolved with better hardware?

Yes, the issue was caused by toyota shared ground. Separate cam sensor harness resolved the issue. Max9924 ic
