### ISSUE TITLE
Tachometer sweep does not work on CANbus tachometer

### ISSUE THREAD

**Issue by rusefillc** [FOME-Tech/fome-fw#482]
https://github.com/FOME-Tech/fome-fw/commit/2ff394e3e9cd8fbf13e8d58633fead04acd48c21 does not work neither for existing CANbus dash profiles nor for Lua CANbus integration

**Comment by mck1117** [comment]
And it's not really supposed to. We send the real values over CAN and allow the dash to do whatever it wants. If the dash is going to do a tach sweep, it does that internally, independent of the ECU.

**Comment by rusefillc** [comment]
So you signal fake RPM for one kind of dashes but not for the other kind of dashes, gotcha!
