### ISSUE TITLE
Logs don't record time in less than second increiments

### ISSUE THREAD

**Issue by alrijleh** [FOME-Tech/fome-fw#484]
In past releases, logs would show the time to the thousandths of a second.  In the current snapshot, logs only show second increments, making it more difficult to examine high speed events.

Observed on hellen64_NA6

You can see that the timescale at the bottom of the log is only is x.000 seconds
![time](https://github.com/user-attachments/assets/30ad4eb0-8601-46c6-b072-67b30582a2fd)

**Comment by mck1117** [comment]
Everything looks fine on my end using a recent log and the same version of MLV...

**Comment by mck1117** [comment]
ah nope the bug is real and it's in 9efd565d296737575c5fe5afe6baf982143978e9

**Comment by mck1117** [comment]
@alrijleh Should be fixed - give it a shot on a fresh snapshot and see what you see.

**Comment by alrijleh** [comment]
Verified fixed in the 2409 release
