### ISSUE TITLE
Disable TPS Error check on Auto Calibration

### ISSUE THREAD

**Issue by dynfer** [FOME-Tech/fome-fw#504]
Hello,
Suggestion to disable TPS error check during the auto calibration procedure. This would allow Toyota installs to use it.
Currently on real way is to calibrate the TPS manually.

**Comment by mck1117** [comment]
what specific behavior do you see that you think is wrong? screenshot/vid?

**Comment by dynfer** [comment]
The throttle just stops at random values due to the TPS error, its not moving smoothly from 0 to 100%.

**Comment by rusefillc** [comment]
> The throttle just stops at random values due to the TPS error, its not moving smoothly from 0 to 100%.

vid? logs? what throttle is that?

**Comment by dynfer** [comment]
@rusefillc I've mainly encountered it with Toyota throttles which require the special setting for the secondary sensor. It basically errors out if setting isn't set right preventing the calibration from finishing.

**Comment by dynfer** [comment]
Solved in #514

**Comment by dynfer** [comment]
Solved in #514
