### ISSUE TITLE
Unable to clone on Windows: README.md and readme.md in same folder

### ISSUE THREAD

**Issue by rusefillc** [FOME-Tech/fome-fw#89]
https://github.com/FOME-Tech/fome-fw/blob/master/firmware/ext/README.md vs https://github.com/FOME-Tech/fome-fw/blob/master/firmware/ext/readme.md is a problem for Windows file system

**Comment by mck1117** [comment]
Even better than case insensitive filesystems are _sometimes_ case insensitive filesystems!

**Comment by mck1117** [comment]
Anyway, should be fixed now.
