### ISSUE TITLE
Adjustable load axis for Idle VE

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [FOME-Tech/fome-fw#90]
For support of certain applications, like ITB, we should add an adjustable fuel mode for idle VE. For example, while you have tps vs rpm on the main ignition and VE tables, you can override the y axis and use MAP instead of TPS on idle VE. 

The idea is to have better idle fuel control for alphaN applications. Other ecus use similar strategies with success. As we get more and more ITB users, it’s important to look into it.

**Comment by mck1117** [comment]
Done.
