### ISSUE TITLE
add date code to firmware folders

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [FOME-Tech/fome-fw#91]
I preferred the old way of each release folder having a date code.  Currently it just wants to overwrite old releases without manual intervention.

**Comment by OrchardPerformance** [comment]
Spotted that earlier, probably a high priority one.

**Comment by mck1117** [comment]
snapshots have date now

![image](https://github.com/FOME-Tech/fome-fw/assets/568254/8bc54ef8-aa65-4f84-a412-40f4f1f496a5)

release builds have release name

![image](https://github.com/FOME-Tech/fome-fw/assets/568254/8876bc5f-4d6f-4c53-8cb7-ea55b44f877b)
