### ISSUE TITLE
TPS MAP fallback table has no axis as default

### ISSUE THREAD

**Issue by OrchardPerformance** [FOME-Tech/fome-fw#93]
Thank you for taking the time to report an issue!

To make our work easier, please provide as many details as you can:
* [ ] What hardware did you use while experiencing the issue?

**Comment by mck1117** [comment]
Can you provide some more context? Not sure what this is asking.

**Comment by OrchardPerformance** [comment]
![image](https://user-images.githubusercontent.com/49926376/236083993-091cd711-d9fd-4697-83aa-61c29a36f73f.png)
This is how it is on a fresh firmware flash at the moment. 

No values for either X or Y axis.

**Comment by mck1117** [comment]
Much better context, thank you!

**Comment by nmschulte** [comment]
Mmm, not sure what's going on here; this is what Proteus F7 build shows on new project load:
![image](https://user-images.githubusercontent.com/8540239/236128845-261b3bf6-3e06-4c01-bfe0-e41a8d6fa237.png)

-21474836.48

**Comment by mck1117** [comment]
Hopefully eventually we delete that table and use #63 instead :)

**Comment by OrchardPerformance** [comment]
Is it bad I'm ok with the idea of killing that table down to a 4x4? With a
view to obsolete it quickly?
